### PR TITLE
Add ForcePathStyle and DisableServerSideEncryption options

### PR DESCRIPTION
**Pull request by codedninja**
Quick patch to add support for `S3ForcePathStyle` and disabling server-side encryption to support using Minio.

### CODE REVIEW

**Comment by yellow-sky** [comment]
Usefull features

**Comment by codedninja** [comment]
Any update on possibly merging these changes?

**Comment by naucon** [comment]
+1

**Comment by alka-dev** [comment]
+1

**Comment by nymo** [comment]
Ping. Any update on this? Would really love to see this feature getting merged.

**Review by funkyshu — APPROVED** [review]

**Pull request merged**
